<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Smart\Video\Block\Product\View\Gallery
 */
?>

<?php if (!empty(json_decode($block->getGalleryVideosJson()))): ?>
    <div class="product-videos product-accordion">
        <div class="videos-title">
            <h3><?php /* @escapeNotVerified */ echo __('Product videos'); ?></h3>
        </div>
        <div class="videos-gallery">
            <div class="gallery-video-placeholder _block-content-loading" data-gallery-role="gallery-video-placeholder">
                <div class="loader">
                    <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
                </div>
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "[data-gallery-role=gallery-video-placeholder]": {
                "mage/gallery/gallery": {
                    "mixins":["magnifier/magnify"],
                    "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                    "data": <?php /* @escapeNotVerified */ echo $block->getGalleryVideosJson(); ?>,
                    "options": {
                        "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                        <?php if (($block->getVar("gallery/loop"))): ?>
                            "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/keyboard"))): ?>
                            "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/arrows"))): ?>
                            "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                            "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/caption"))): ?>
                            "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                        <?php endif; ?>
                        "width": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
                        "thumbwidth": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'width'); ?>",
                        <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                            ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                        <?php endif; ?>
                        <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                            "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                            ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/transition/duration")): ?>
                            "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                        <?php endif; ?>
                        "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                        <?php if (($block->getVar("gallery/navarrows"))): ?>
                            "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                        <?php endif; ?>
                        "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                        "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>"
                    },
                    "fullscreen": {
                        "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                        <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                            "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                        <?php endif; ?>
                        "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                        <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                            "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navarrows"); ?>,
                        <?php endif; ?>
                        "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navtype"); ?>",
                        <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                            "arrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                            "showCaption": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/caption"); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                            "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                        <?php endif; ?>
                        "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                    },
                    "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
                }
            }
        }
    </script>
<?php endif; ?>